---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 158.160.41.246 #Адрес машины
        vm_2:
          ansible_host: 158.160.50.36
        vm_3:
          ansible_host: 158.160.58.69

  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    ansible_password: ""
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения
